### ISSUE TITLE
Wan't add some notice when block hide

### ISSUE THREAD

**Issue by wangcode** [ndiego/block-visibility#1]
If i wan't add some notice when block hide, how can i do this

**Comment by ndiego** [comment]
Hi @wangcode if I am understanding your question correctly, the best way to do this is create another block with the content that you want people to see when the initial block(s) is hidden, and set the inverse visibility settings. 

So for example, say you had a form that you have set to only show to logged-in users. You would create the notice (perhaps a cover block) to only show to logged-out users, and it could say something like "Log in to view the form". 

Let me know if that doesn't answer your question.

**Comment by wangcode** [comment]
thanks @ndiego , There's no problem with your understanding, I'm already using the solution just like you told me.
Thank you for your help, have a good day. 
: )

**Comment by ndiego** [comment]
Awesome, glad it is working for you!
