### ISSUE TITLE
Add custom code snippets in <head>

### ISSUE THREAD

**Issue by JosVelasco** [ndiego/block-visibility#103]
## What problem does this address?
Inject snippets to a website's <head> section, controlling their visibility.

## What is your proposed solution?
In the settings of a block, add a field to insert custom code.

This could be an interesting approach to an option lacking in the Site Editor: [inserting code without touching files](https://github.com/WordPress/gutenberg/issues/52091).

**Comment by ndiego** [comment]
This is a cool idea, but not something I would consider for Block Visibility. The plugin should really only be controlling the visibility of blocks, but injecting code itself.
