### ISSUE TITLE
cookie_value_compare function 'contains' does not work

### ISSUE THREAD

**Issue by SerhiiMazurBeetroot** [ndiego/block-visibility#110]
## Description

This is my first experience with your plugin. And I realized that the "value contains" cookie visibility rule is not working properly.

## Step-by-step reproduction instructions

1. Add controls 'Cookie'
2. Fill in the cookie_name: 'cookie_name'
3. Select 'value contains'
4. Enter: 'value1, value2' or 'value1 value2'
5. It doesn't work

## Expected behavior

This should work

## Actual behavior

It doesn't work

## Screenshots or screen recording (optional)

![Vc496C8](https://github.com/user-attachments/assets/c422fd2f-99df-41be-aea8-47296c18d6ca)

## System information
- Block Visibility version: "3.5.0"
- Block Visibility Pro version: "Not installed"
- WordPress version: 6.5.5"
- Gutenberg version: "Not installed"
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? "Yes" 
- Are you using a default theme (e.g. Twenty Twenty-One)? "No"

**Comment by ndiego** [comment]
Thanks for logging this issue. However, it seems to be working properly for me. This is my testing setup. 

| Cookie | Visibility settings |
|-|-|
|<img width="706" alt="image" src="https://github.com/user-attachments/assets/4bb14fc5-28ec-434c-ab2a-111997519ef5">|<img width="389" alt="image" src="https://github.com/user-attachments/assets/a4be1fbc-74a9-4f04-bffb-78a031b9620c">|

Note that the value field **does not** support multiple options. Currently, if you want to check for multiple values and create an OR condition, you need to add an additional Rule Set, like this: 

<img width="569" alt="image" src="https://github.com/user-attachments/assets/af58175b-3ca2-4529-9113-476502cbd090">

**Comment by ndiego** [comment]
> Did you plan to add an option to enter multiple values ​​to compare to the cookie (in case it has single value)?

Perhaps in the future, but this is the first time it's been requested. Using multiple Rule Sets, as outlined in the comment above, does provide a solution when you need to evaluate multiple values using an OR condition. If you need to compare multiple values using an AND condition, you can add an additional rule to the same Rule Set. See below for both setups.

| OR condition | AND condition |
|-|-|
|<img width="561" alt="image" src="https://github.com/user-attachments/assets/04cef708-31a9-449f-ac80-da15a3f63cbf">|<img width="561" alt="image" src="https://github.com/user-attachments/assets/7210578c-f64f-4f24-904c-cdbabeb63cbd">|

So, while I agree that being able to add multiple values to the field would be easier, you can still accomplish what you are looking for using the existing setup.
