### ISSUE TITLE
Looking through various settings.

### ISSUE THREAD

**Issue by paaljoachim** [ndiego/block-visibility#15]
Hey Nick

I am retesting your plugin. Doing a quick test. Looking through plugin settings and Gutenberg sidebar settings.

Activating and clicking settings leads me to Settings -> Block Visibility.

I notice a popup with a message with the title: "Thank you for using Block Visibility"
Spelling error: recieve -> receive

I see the information within the Block Editor area. Wonder what some of these are and then click the i (tool tip) for additional information. That is very helpful!

A very clean settings page with a nice overview of various features!

---------

Going to an existing page. Clicking a Cover block.
Opening the sidebar settings area and checking out Visibility controls.

Wow you are actually using the new progressive disclosure panel. Which is brand new in Gutenberg.

![Screen Shot 2021-07-07 at 22 39 02](https://user-images.githubusercontent.com/5323259/124825603-267f2800-df74-11eb-8cf2-662caab793e2.png)

There is also a PR being worked on here for Gutenberg:
Dimensions Panel: Add new progressive disclosure panel and update spacing supports
https://github.com/WordPress/gutenberg/pull/32392

There are a lot of powerful options there.
Ending the test here for this mini round.

**Comment by ndiego** [comment]
Thanks for the review and feedback @paaljoachim. That spelling error will be fixed in the next release 😅

I also commented over in that Dimensions Panel PR. Very interesting stuff!

**Comment by paaljoachim** [comment]
I will just go ahead and close this issue for now. (I can always reopen if need be.)
