### ISSUE TITLE
Feature Request: URL Path matches and/or "Is a descendent of"

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/block-visibility#16]
## What problem does this address?
Largely in the context of Blocks as Widgets (or other full-site-editing), I think this plugin could really benefit from some more flexible Location style rules.  Let's say I have a Gardening website, and I have sections for things like Flowers, Fruits, Vegetables, etc.  I'd love to be able to say: "This block only shows up in I'm on the /flowers/ page, or any child pages of that page."

## What is your proposed solution?
I see two primary methods - but both have their own merits and they could certainly coexist.

1) Include a rule for matching URLs.  That is, show the block if the URL contains "mysite.com/flowers".  This would make it appear on the Flowers landing page, and any child pages that are descendants of it.

2) Include the option for including descendent posts automatically. 
Currently, I can choose the following:
Show the block if
Post
Page
Is any of the Selected
Flowers.

What if there was a checkbox that said: "Include child/descendent posts" automatically? This would prevent users from having to go back and add another child-page to the block rules each time they add a new child page in that section.

**Comment by ndiego** [comment]
This request is great, thanks for adding it @MadtownLems. I am thinking that probably both options would be good. I see the Location control being a bit more advanced. So it would be nice to have a dedicated control specifically for URL Path. I will let you know when I begin working on this.

**Comment by ndiego** [comment]
Closing this out as the URL control has been added to Block Visibility Pro.
