### ISSUE TITLE
Feature Request: Support Reusable Rule Sets

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/block-visibility#17]
## What problem does this address?
If I craft a complex rule set, it's cumbersome to apply it to multiple blocks that all want the same ruleset. And then if I want to modify the ruleset, I need to remember exactly which blocks on the site were using it so I can go back and find them all.

## What is your proposed solution?
Support the concept of "Reusable Rule Sets".

I would love to be able to craft a complex rule set, and apply it to multiple blocks easily. (that is, just select a predefined rule set in the Block Visibility settings rather than do all the settings again.)

A sample use case: Black Friday Promotion

I could craft a complex rule set such as:

Only during a certain time frame
Only to users to aren't logged in
Only show if a certain URL parameter exists.

Then, each time I want a block to follow these rules, I just choose my existing rule set "Black Friday 2021 Promotion".
Then, if I decide to extend the promotion, I can easily adjust the schedule in one place, etc.

**Comment by ndiego** [comment]
I have already started sketching out the implementation of Rule Sets and will likely begin development on this next week. This has been a popular request (#3 ). This will be included in the free version, but the Pro functionality will be available in sets if the add-on is enabled.

**Comment by ndiego** [comment]
This is now possible in Block Visibility Pro with the implementation of [Presets](https://blockvisibilitywp.com/knowledge-base/guide-to-visibility-presets/).
