### ISSUE TITLE
Feature request: Show/hide block after N days since last purchase of specific product

### ISSUE THREAD

**Issue by procontentxyz** [ndiego/block-visibility#2]
First of all thank you for such an amazing plugin.

You already promised for this feature:
"Show a block when someone has purchased something from your WooCommerce store..."

In addition, I want to request some thing:

Show a block when someone has purchased something from our WooCommerce store +
Let this also expire by number of hours/days since the date of purchase.

This way your plugin can be used as a Pay Per View (Block) plugin with Hours/Days based expire after purchasing any specific woocommerce product.

If you implemented this feature, your plugin will be rocking.

God bless you.

One tip for you:

Instead of using CRON (if you are using it)

Use new modern method suggested by WordPress:

That is action scheduler API:

Ref: https://actionscheduler.org/ (provided by wordpress)

Ref: https://woocommerce.github.io/code-reference/namespaces/default.html#function_wc_customer_bought_product (inbuilt function to check if bought)

I don't know why but I think:

This plugin can prove as a life saver for many of us!

Using your plugin will help too much for all.

Please consider this feature that I have shared above.

**Content Future is: pay per view with expiry (hours/days)**

**Comment by ndiego** [comment]
Hi @procontentxyz thanks for the feature request. While I have not started work on the Woocommerce integration, it is planned for later this spring. I am working on solidifying the core of the plugin, and building out the plugin website with complete documentation, and then will start on third-party integrations. Woocommerce is number 1 though! 

Also I really appreciate the function references, I am by no means a Woocommerce expert, so building the integration will be a bit of a learning experience. 

When I begin work on the integrations, I will reference this ticket. Thanks!

**Comment by procontentxyz** [comment]
No worries thank you!

I will wait :)

**Comment by ndiego** [comment]
Please to say that this functionality is now available in the Pro add-on. More details available here: https://www.blockvisibilitywp.com/pro-version-1-2-0-ecommerce-enhancements-metadata-control-copy-import-new-pricing-and-more/
