### ISSUE TITLE
Add option to automatically remove a Block when the schedule is over

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/block-visibility#23]
## What problem does this address?
If a site uses a lot of scheduled blocks, it could easily get littered with blocks that are past their scheduled dates - never to be shown again - but clogging up page editing screens. It would be great if I could say that "This block stops showing on Date X and then should be removed from the content."

## What is your proposed solution?
Add a checkbox to Schedule logic that says something like: "Remove this block after the last scheduled interval."

Then, when parsing the page's blocks for conditional display, if a block's scheduled logic has passed and this option was selected, remove the block from the page completely.

**Comment by ndiego** [comment]
I can definitely see how this functionality would be useful, but I want to stay away from actually removing block content from the Editor. That said some improvement to the conditional indicators, or separate UI enhancement, could make blocks past their scheduled dates more prominent without having to click in and view the settings. This would allow users to more easily remove unneeded content themselves. Will consider this in version 2.4+
