### ISSUE TITLE
Feature request: Trigger according to a global "variable"

### ISSUE THREAD

**Issue by lstep** [ndiego/block-visibility#3]
Hello,
A feature that would be nice, would be to have some kind of "global" variable (a boolean for example) that would be tested for value to activate or no a block. My use case is that I have a dozen of pages where I have a specific block element that I want to activate/deactivate all at the same time, but not according to a time parameter. If there was a variable that could be tested...

**Comment by ndiego** [comment]
This is now possible in Block Visibility Pro with the implementation of [Presets](https://blockvisibilitywp.com/knowledge-base/guide-to-visibility-presets/).
