### ISSUE TITLE
Display text that matches url string

### ISSUE THREAD

**Issue by hashimwarren** [ndiego/block-visibility#41]
## What problem does this address?

Advertisers create many different ad variations that lead to the same landing page. Unfortunately this can create a messaging mismatch between the ad and landing page which causes confusion and a lower conversation rate. 
## What is your proposed solution?

Enable a block's text to change based on the text in a url. For example the copy of headline block could be "Free Ebook for Developers"

If the URL string includes example.com/?headline=free+ebook+for+WordPress+developers

... Then the copy in the block should change to "Free Ebook for WordPress Developers"

The block should have a default key, but also allow the user to change the key to something like "headline".

When I was a full time advertiser, "Dynamic Text Replacement" was a heavily used Unbounce feature for my team https://documentation.unbounce.com/hc/en-us/articles/203661004-Working-with-Dynamic-Text-Replacement

It allowed us to experiment with and deploy new messaging rapidly, without having to create completely new landing pages.

Block visibility does allow changes based on the URL string, but this feature proposal is more flexible because you do not need to know the text change beforehand.

**Comment by ndiego** [comment]
This is a cool idea, but outside the scope of Block Visibility. The plugin should not modify the content of a block in any way, just display it or not.
