### ISSUE TITLE
ACF rule set with equal rule doesn't work properly

### ISSUE THREAD

**Issue by land0r** [ndiego/block-visibility#50]
## Description

For numeric ACF values, there is no proper working for the rule set because the condition in PHP is strict - https://github.com/ndiego/block-visibility/blob/main/includes/frontend/visibility-tests/acf.php#L205

If you remove `===` to `==` or try to add some type for this check, there will be the desired result.

## Step-by-step reproduction instructions

1. Add any block (paragraph) to Gutenberg.
2. Add a rule set with ACF. ACF rule is "Show the block if 'Numeric ACF' is equal to 12" 
3. Save the page

## Expected behavior
You will see this block because the code tries to compare 12 == '12' (integer with string but without strict comparison)

## Actual behavior

You will not see this block because the code tries to compare 12 === '12' (integer with string)

## Screenshots or screen recording (optional)

![2022-11-15 15 26 58 iq-foundertrac test ef64fe07381e](https://user-images.githubusercontent.com/16062994/201931176-50469fbc-4728-40b8-b743-4361a4a475e1.png)

## System information
- Block Visibility version: 2.4.6
- Block Visibility Pro version: Not installed
- WordPress version: 6.1
- Gutenberg version: "Not installed" as a plugin, used from Core
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by v-vovk** [comment]
I totally agree with you, it's a very annoying thing

**Comment by ndiego** [comment]
@land0r Thanks for reporting this, and I apologize for the delayed reply. This will be fixed in the next version, scheduled for 2022-12-05.
