### ISSUE TITLE
Block visibility support for blocks with parent

### ISSUE THREAD

**Issue by land0r** [ndiego/block-visibility#59]
## What problem does this address?

The plugin has a limitation for visibility settings if a block has parent property. But in my case, I need an exception for my custom block with a custom parent parameter (not core/columns > core/column). 

## What is your proposed solution?

It would be great if you can add here some filters or give me the possibility to include my custom blocks in allow list even with parent property. Thanks!
https://github.com/ndiego/block-visibility/blob/ca14d333006c7551a67dbe2339e286e4339c2828/src/settings/block-manager/index.js#L100

**Comment by ndiego** [comment]
Hi @land0r, can you try enabling [Full Control Mode](https://blockvisibilitywp.com/knowledge-base/how-to-configure-the-general-settings/#h-full-control-mode) in the plugin settings? This should enable Visibility settings for all child blocks. Let me know if this fixes things. Thanks!

**Comment by land0r** [comment]
@ndiego yeah, it is working. Thanks! I suppose the issue is resolved and we can close it

**Comment by ndiego** [comment]
Wonderful, glad it is working for you. Closing out the ticket.
