### ISSUE TITLE
After updating to 3.0.0, the plugin does not detect translations in Editor

### ISSUE THREAD

**Issue by Gierand** [ndiego/block-visibility#68]
## Description

Does not detect translation to other languages in the Site/Post/Page Editor. On the settings page everything works fine.

## Step-by-step reproduction instructions
 
1. Add sample translated files to the directory:
`/wp-content/languages/plugins/block-visibility-de_DE.mo`
`/wp-content/languages/plugins/block-visibility-de_DE-2b47503f90344d6580630a5c3c521589.json`
`/wp-content/languages/plugins/block-visibility-de_DE-528469e0eb827b69963521f596eeae41.json`
2. Check Editor if the translation has been detected.

## System information
- Block Visibility version: 3.0.0
- WordPress version: 6.1.1 & 6.2-RC4
- Gutenberg version: 15.4.0
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-Three)? Yes

**Comment by ndiego** [comment]
Thanks for reporting @Gierand, I'll look into it! 💪

**Comment by ndiego** [comment]
Fixed in v3.0.1.

**Comment by Gierand** [comment]
Thank you!

**Comment by Gierand** [comment]
@ndiego, Yet another little thing. The string "Custom Sets" does not have a text domain.

![bv](https://user-images.githubusercontent.com/1615208/227934588-8b4fe1e2-7bfa-46e9-bbfa-98a03ff1fc43.png)

**Comment by ndiego** [comment]
You are 100% correct. That string is missing a text domain 🤦‍♂️ I'll get that fixed up in the next release.
