### ISSUE TITLE
The block_visibility_is_block_visible filter is ignored.

### ISSUE THREAD

**Issue by BlaineMoore** [ndiego/block-visibility#69]
## Description

My use case: I am creating a new website and moving off of some old technologies, and am looking to use WP Fusion and Block Visibility going forward. We require our site to have "bypass" links which would allow a visitor using a specific link to view a page even if certain content would normally require a user to be logged in and have a specific membership level. 

For a working example, here's our current website (not using Block Visibility), if you visit this page, you'll be told to signin or signup:
[https://apexauthors.com/introduction-to-self-publishing/](https://apexauthors.com/introduction-to-self-publishing/)
However, if you visit _this_ link, then it will treat you as though you were logged in with the right membership level even if you aren't logged in:
[https://apexauthors.com/introduction-to-self-publishing/?key=2b4dd2fb2f8598caf8b8ed6f917dec5f](https://apexauthors.com/introduction-to-self-publishing/?key=2b4dd2fb2f8598caf8b8ed6f917dec5f)

When using the _block_visibility_is_block_visible_ filter to control access, however, it is ignoring the filter when a user is not logged in because it hard-codes the user as not having access after the filter is applied.

## Step-by-step reproduction instructions
1. Create a block, set a user role (logged in, or subscriber, or any valid option so a normal link will appear if they fit that user role), save the page.
2. Visit the page; if you are logged in, it appears. If you are not, it won't.
3. Add the following code to your functions.php file:
```php
add_filter( 'block_visibility_is_block_visible', 'private_tags_bypass_bv_check', 15,3 );
function private_tags_bypass_bv_check($is_visible, $settings, $controls) { return true; }
```
4. Visit the page; if you are logged in, it appears. If you are not, it still won't.

(In my actual use case, I have a plugin which decides if the block should be visible or not depending on other criteria, but the above reproduction steps are an easy way to spot the bug.)

## Expected behavior
The filter should be able to control the block visibility.

## Actual behavior
The filter is ignored if the user is not logged in.

## Screenshots or screen recording (optional)
![Screenshot of a random visitor and a logged in user](https://www.evernote.com/shard/s187/sh/da76f013-40ad-4def-9b24-a607dc9bccf4/CoPPc8vgRcQdlwm6Yq0SReKsJtARzxAxIZ8lLSOz8t0zoaTNDcGX_6W69g/deep/0/image.png)

## System information
- Block Visibility version: 3.0.2
- Block Visibility Pro version: Not installed
- WordPress version: 6.2
- Gutenberg version: WordPress Core
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? Yes*
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes* 

*Screenshot is from my previous testing but I have confirmed on just the default settings as requested.

**Comment by BlaineMoore** [comment]
Got a reply from @ndiego in the [WordPress support forum](https://wordpress.org/support/topic/the-block_visibility_is_block_visible-filter-is-ignored/#post-16696802) that solved my issue exactly (only had to swap out the filters as listed below and my plugin started working flawlessly.)

> Hi [@blaine-moore](https://wordpress.org/support/users/blaine-moore/),
> 
> Thanks for reaching out. Can you give the ```block_visibility_control_set_is_block_visible``` filter a try? As you mentioned, ```block_visibility_is_block_visible``` is called too early for what you are trying to do.
> 
> Let me know if that works, or if you continue to run into any issues.
> 
> Best,
> Nick

**Comment by ndiego** [comment]
Thanks @BlaineMoore, and sorry for missing this issue earlier!
