### ISSUE TITLE
tore "core/interface" is already registered.

### ISSUE THREAD

**Issue by krstivoja** [ndiego/block-visibility#98]
<img width="2560" alt="Screenshot 2024-02-13 at 10 26 25" src="https://github.com/ndiego/block-visibility/assets/1234350/eaaa37bd-43d7-4b32-804e-c6d60db728f2">

Disabled all other plugins

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Open template parts header
-->

## System information
- Block Visibility version: Version 3.3.0 
- WordPress version: 6.3.3
- Gutenberg version: "Not installed"
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? Only active plugin
- Are you using a default theme custom blank theme and 20-23

**Comment by ndiego** [comment]
Thanks for opening, @krstivoja. Unfortunately, This issue needs to wait for a fix in Core. Here is the related issue: https://github.com/WordPress/gutenberg/pull/60033

The error in the Site Editor is harmless, but it's definitely annoying that it shows up in the console.

**Comment by ndiego** [comment]
Looks like this has been fixed in Core and I am no longer seeing this issue in WordPress 6.6.

**Comment by krstivoja** [comment]
Thanks for the update @ndiego
