### ISSUE TITLE
wp.date.__experimentalGetSettings is deprecated

### ISSUE THREAD

**Issue by huubl** [ndiego/block-visibility#99]
## Description
[wp.date.__experimentalGetSettings](https://github.com/search?q=repo%3Andiego%2Fblock-visibility%20__experimentalGetSetting%20&type=code) is deprecated since version 6.1. Please use wp.date.getSettings instead.

## Step-by-step reproduction instructions

1. Enable debug
2. Select "DATE & TIME" visibility for a block
3. See developer console

or 
https://playground.wordpress.net/?plugin=block-visibility&plugin=debug-this&wp=6.4&url=/wp-admin/post.php%3Fpost%3D1%26action%3Dedit

Paste and see developer console
```
<!-- wp:paragraph {"blockVisibility":{"controlSets":[{"id":1,"enable":true,"controls":{"dateTime":{"schedules":[{"enable":true,"start":"","end":""}]}}}]}} -->
<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
<!-- /wp:paragraph -->
```

## Expected behavior
-

## Actual behavior
-

## System information
- Block Visibility version: 3.3.0
- Block Visibility Pro version: Not installed
- WordPress version: 6.4
- Gutenberg version: Not installed
- Are all plugins except Block Visibility, Block Visibility Pro (if installed), and Gutenberg (if installed) deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

**Comment by ndiego** [comment]
Thanks for reporting @huubl. This has now been fixed in [1fe904f](https://github.com/ndiego/block-visibility/commit/1fe904f1199bcb9b1e48a36ff491b4dc954b73de) and will be included in the next release.
